name: py build project

on:
  push:
    branches:
      - main
jobs:
  pybuildjob1:
    runs-on: ubuntu-latest
    steps:
      - name: pybuildstep1
        uses: actions/checkout@v4
      - name: pybuildsubtest    
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - name: installing dependencies
        run: pip install -r requirements.txt
      - name: executing test case
        run: pytest  
